/*
# Espresso X — Seed Products and Rewards

Seeds the product catalog (16 items) and rewards catalog (8 items) with full customization options.
These are public-read tables used for menu browsing.
*/

DO $$
BEGIN
  -- Products
  INSERT INTO products (id, name, category, description, price, image, rating, popular, seasonal, ai_recommended, in_stock, calories, allergens, sizes, milks, syrups, toppings, temperature, ice_levels, nutrition, sort_order) VALUES
  ('p1', 'Velvet Gold Espresso', 'Espresso', 'Tek menşeili Etiyopya çekirdeklerinden çekilen imza double shot espressomuz, altın rengi krema ile taçlandırılmış.', 220, 'https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg?auto=compress&cs=tinysrgb&w=800', 4.9, true, false, false, true, 10, '{}',
    '[{"id":"s","label":"Küçük","priceModifier":0},{"id":"l","label":"Büyük","priceModifier":10}]'::jsonb,
    '[{"id":"whole","label":"Tam Yağlı Süt","priceModifier":0},{"id":"skim","label":"Yağsız Süt","priceModifier":0},{"id":"oat","label":"Yulaf Sütü","priceModifier":0.6},{"id":"almond","label":"Badem Sütü","priceModifier":0.6},{"id":"soy","label":"Soya Sütü","priceModifier":0.5},{"id":"coconut","label":"Hindistan Cevizi Sütü","priceModifier":0.6}]'::jsonb,
    '[{"id":"none","label":"Şurup Yok","priceModifier":0},{"id":"vanilla","label":"Vanilya","priceModifier":0.5},{"id":"caramel","label":"Karamel","priceModifier":0.5},{"id":"hazelnut","label":"Fındık","priceModifier":0.5},{"id":"pistachio","label":"Antep Fıstığı","priceModifier":0.7},{"id":"lavender","label":"Lavanta Balı","priceModifier":0.7},{"id":"brown-sugar","label":"Kahverengi Şeker","priceModifier":0.5}]'::jsonb,
    '[{"id":"none","label":"Ekstra Yok","priceModifier":0},{"id":"whip","label":"Krema","priceModifier":0.6},{"id":"caramel-drizzle","label":"Karamel Sos","priceModifier":0.5},{"id":"cocoa","label":"Kakao","priceModifier":0.3},{"id":"cinnamon","label":"Tarçın","priceModifier":0.3},{"id":"gold-leaf","label":"Altın Yaprak","priceModifier":2.5}]'::jsonb,
    '[{"id":"hot","label":"Sıcak","priceModifier":0}]'::jsonb,
    '["Buz Yok"]'::jsonb,
    '{"calories":10,"fat":0,"carbs":1,"protein":0,"caffeine":150}'::jsonb, 1),
  ('p2', 'Kakule Latte', 'Latte', 'Zengin espresso tabanı üzerine kavrulmuş kakule tohumları ile buharlaştırılan ipeksi mikro köpük. Ev imzası.', 220, 'https://images.pexels.com/photos/302901/pexels-photo-302901.jpeg?auto=compress&cs=tinysrgb&w=800', 4.8, true, true, true, true, 180, '{Süt}',
    '[{"id":"s","label":"Küçük","priceModifier":0},{"id":"l","label":"Büyük","priceModifier":10}]'::jsonb,
    '[{"id":"whole","label":"Tam Yağlı Süt","priceModifier":0},{"id":"skim","label":"Yağsız Süt","priceModifier":0},{"id":"oat","label":"Yulaf Sütü","priceModifier":0.6},{"id":"almond","label":"Badem Sütü","priceModifier":0.6},{"id":"soy","label":"Soya Sütü","priceModifier":0.5},{"id":"coconut","label":"Hindistan Cevizi Sütü","priceModifier":0.6}]'::jsonb,
    '[{"id":"none","label":"Şurup Yok","priceModifier":0},{"id":"vanilla","label":"Vanilya","priceModifier":0.5},{"id":"caramel","label":"Karamel","priceModifier":0.5},{"id":"hazelnut","label":"Fındık","priceModifier":0.5},{"id":"pistachio","label":"Antep Fıstığı","priceModifier":0.7},{"id":"lavender","label":"Lavanta Balı","priceModifier":0.7},{"id":"brown-sugar","label":"Kahverengi Şeker","priceModifier":0.5}]'::jsonb,
    '[{"id":"none","label":"Ekstra Yok","priceModifier":0},{"id":"whip","label":"Krema","priceModifier":0.6},{"id":"caramel-drizzle","label":"Karamel Sos","priceModifier":0.5},{"id":"cocoa","label":"Kakao","priceModifier":0.3},{"id":"cinnamon","label":"Tarçın","priceModifier":0.3},{"id":"gold-leaf","label":"Altın Yaprak","priceModifier":2.5}]'::jsonb,
    '[{"id":"hot","label":"Sıcak","priceModifier":0},{"id":"iced","label":"Buzlu","priceModifier":0},{"id":"blended","label":"Blended","priceModifier":0.8}]'::jsonb,
    '["Buz Yok","Az Buzlu","Normal","Ekstra Buzlu","Blended"]'::jsonb,
    '{"calories":180,"fat":7,"carbs":18,"protein":8,"caffeine":154}'::jsonb, 2),
  ('p3', 'Bal Peteği Cappuccino', 'Cappuccino', 'Klasik 1:1:1 espresso, buharlaştırılmış süt ve sıkı köpük, yaban çiçeği bal peteği şurubu ile öpülmüş.', 220, 'https://images.pexels.com/photos/2074130/pexels-photo-2074130.jpeg?auto=compress&cs=tinysrgb&w=800', 4.7, true, false, false, true, 140, '{Süt}',
    '[{"id":"s","label":"Küçük","priceModifier":0},{"id":"l","label":"Büyük","priceModifier":10}]'::jsonb,
    '[{"id":"whole","label":"Tam Yağlı Süt","priceModifier":0},{"id":"skim","label":"Yağsız Süt","priceModifier":0},{"id":"oat","label":"Yulaf Sütü","priceModifier":0.6},{"id":"almond","label":"Badem Sütü","priceModifier":0.6},{"id":"soy","label":"Soya Sütü","priceModifier":0.5},{"id":"coconut","label":"Hindistan Cevizi Sütü","priceModifier":0.6}]'::jsonb,
    '[{"id":"none","label":"Şurup Yok","priceModifier":0},{"id":"vanilla","label":"Vanilya","priceModifier":0.5},{"id":"caramel","label":"Karamel","priceModifier":0.5},{"id":"hazelnut","label":"Fındık","priceModifier":0.5},{"id":"pistachio","label":"Antep Fıstığı","priceModifier":0.7},{"id":"lavender","label":"Lavanta Balı","priceModifier":0.7},{"id":"brown-sugar","label":"Kahverengi Şeker","priceModifier":0.5}]'::jsonb,
    '[{"id":"none","label":"Ekstra Yok","priceModifier":0},{"id":"whip","label":"Krema","priceModifier":0.6},{"id":"caramel-drizzle","label":"Karamel Sos","priceModifier":0.5},{"id":"cocoa","label":"Kakao","priceModifier":0.3},{"id":"cinnamon","label":"Tarçın","priceModifier":0.3},{"id":"gold-leaf","label":"Altın Yaprak","priceModifier":2.5}]'::jsonb,
    '[{"id":"hot","label":"Sıcak","priceModifier":0},{"id":"iced","label":"Buzlu","priceModifier":0}]'::jsonb,
    '["Buz Yok","Az Buzlu","Normal","Ekstra Buzlu","Blended"]'::jsonb,
    '{"calories":140,"fat":5,"carbs":16,"protein":7,"caffeine":150}'::jsonb, 3),
  ('p4', 'Gece Yarısı Cold Brew', 'Cold Brew', 'Olağanüstü pürüzsüz, düşük asiditeli, bitter çikolata notalarına sahip bir fincan için soğuk kaynak suda 20 saat demlendi.', 220, 'https://images.pexels.com/photos/894695/pexels-photo-894695.jpeg?auto=compress&cs=tinysrgb&w=800', 4.9, true, false, true, true, 15, '{}',
    '[{"id":"s","label":"Küçük","priceModifier":0},{"id":"l","label":"Büyük","priceModifier":10}]'::jsonb,
    '[{"id":"whole","label":"Tam Yağlı Süt","priceModifier":0},{"id":"skim","label":"Yağsız Süt","priceModifier":0},{"id":"oat","label":"Yulaf Sütü","priceModifier":0.6},{"id":"almond","label":"Badem Sütü","priceModifier":0.6},{"id":"soy","label":"Soya Sütü","priceModifier":0.5},{"id":"coconut","label":"Hindistan Cevizi Sütü","priceModifier":0.6}]'::jsonb,
    '[{"id":"none","label":"Şurup Yok","priceModifier":0},{"id":"vanilla","label":"Vanilya","priceModifier":0.5},{"id":"caramel","label":"Karamel","priceModifier":0.5},{"id":"hazelnut","label":"Fındık","priceModifier":0.5},{"id":"pistachio","label":"Antep Fıstığı","priceModifier":0.7},{"id":"lavender","label":"Lavanta Balı","priceModifier":0.7},{"id":"brown-sugar","label":"Kahverengi Şeker","priceModifier":0.5}]'::jsonb,
    '[{"id":"none","label":"Ekstra Yok","priceModifier":0},{"id":"whip","label":"Krema","priceModifier":0.6},{"id":"caramel-drizzle","label":"Karamel Sos","priceModifier":0.5},{"id":"cocoa","label":"Kakao","priceModifier":0.3},{"id":"cinnamon","label":"Tarçın","priceModifier":0.3},{"id":"gold-leaf","label":"Altın Yaprak","priceModifier":2.5}]'::jsonb,
    '[{"id":"iced","label":"Buzlu","priceModifier":0}]'::jsonb,
    '["Buz Yok","Az Buzlu","Normal","Ekstra Buzlu","Blended"]'::jsonb,
    '{"calories":15,"fat":0,"carbs":2,"protein":1,"caffeine":220}'::jsonb, 4),
  ('p5', 'Filtre Kahve', 'Filtre Kahve', 'Tek menşeili Kolombiya kavrumu, küçük partiler halinde el ile dökülerek demlenir. Parlak sitrus, temiz bitiş.', 220, 'https://images.pexels.com/photos/414645/pexels-photo-414645.jpeg?auto=compress&cs=tinysrgb&w=800', 4.6, false, false, false, true, 5, '{}',
    '[{"id":"s","label":"Küçük","priceModifier":0},{"id":"l","label":"Büyük","priceModifier":10}]'::jsonb,
    '[{"id":"whole","label":"Tam Yağlı Süt","priceModifier":0},{"id":"skim","label":"Yağsız Süt","priceModifier":0},{"id":"oat","label":"Yulaf Sütü","priceModifier":0.6},{"id":"almond","label":"Badem Sütü","priceModifier":0.6},{"id":"soy","label":"Soya Sütü","priceModifier":0.5},{"id":"coconut","label":"Hindistan Cevizi Sütü","priceModifier":0.6}]'::jsonb,
    '[{"id":"none","label":"Şurup Yok","priceModifier":0},{"id":"vanilla","label":"Vanilya","priceModifier":0.5},{"id":"caramel","label":"Karamel","priceModifier":0.5},{"id":"hazelnut","label":"Fındık","priceModifier":0.5},{"id":"pistachio","label":"Antep Fıstığı","priceModifier":0.7},{"id":"lavender","label":"Lavanta Balı","priceModifier":0.7},{"id":"brown-sugar","label":"Kahverengi Şeker","priceModifier":0.5}]'::jsonb,
    '[{"id":"none","label":"Ekstra Yok","priceModifier":0},{"id":"whip","label":"Krema","priceModifier":0.6},{"id":"caramel-drizzle","label":"Karamel Sos","priceModifier":0.5},{"id":"cocoa","label":"Kakao","priceModifier":0.3},{"id":"cinnamon","label":"Tarçın","priceModifier":0.3},{"id":"gold-leaf","label":"Altın Yaprak","priceModifier":2.5}]'::jsonb,
    '[{"id":"hot","label":"Sıcak","priceModifier":0}]'::jsonb,
    '["Buz Yok"]'::jsonb,
    '{"calories":5,"fat":0,"carbs":1,"protein":0,"caffeine":145}'::jsonb, 5),
  ('p6', 'Matcha Reserve', 'Matcha', 'Seremoni kalite Uji matcha, kadifemsi buharlaştırılmış süt ile çırpılır. Taş öğütülmüş, ilk hasat.', 220, 'https://images.pexels.com/photos/2304771/pexels-photo-2304771.jpeg?auto=compress&cs=tinysrgb&w=800', 4.8, true, false, true, true, 120, '{Süt}',
    '[{"id":"s","label":"Küçük","priceModifier":0},{"id":"l","label":"Büyük","priceModifier":10}]'::jsonb,
    '[{"id":"whole","label":"Tam Yağlı Süt","priceModifier":0},{"id":"skim","label":"Yağsız Süt","priceModifier":0},{"id":"oat","label":"Yulaf Sütü","priceModifier":0.6},{"id":"almond","label":"Badem Sütü","priceModifier":0.6},{"id":"soy","label":"Soya Sütü","priceModifier":0.5},{"id":"coconut","label":"Hindistan Cevizi Sütü","priceModifier":0.6}]'::jsonb,
    '[{"id":"none","label":"Şurup Yok","priceModifier":0},{"id":"vanilla","label":"Vanilya","priceModifier":0.5},{"id":"caramel","label":"Karamel","priceModifier":0.5},{"id":"hazelnut","label":"Fındık","priceModifier":0.5},{"id":"pistachio","label":"Antep Fıstığı","priceModifier":0.7},{"id":"lavender","label":"Lavanta Balı","priceModifier":0.7},{"id":"brown-sugar","label":"Kahverengi Şeker","priceModifier":0.5}]'::jsonb,
    '[{"id":"none","label":"Ekstra Yok","priceModifier":0},{"id":"whip","label":"Krema","priceModifier":0.6},{"id":"caramel-drizzle","label":"Karamel Sos","priceModifier":0.5},{"id":"cocoa","label":"Kakao","priceModifier":0.3},{"id":"cinnamon","label":"Tarçın","priceModifier":0.3},{"id":"gold-leaf","label":"Altın Yaprak","priceModifier":2.5}]'::jsonb,
    '[{"id":"hot","label":"Sıcak","priceModifier":0},{"id":"iced","label":"Buzlu","priceModifier":0},{"id":"blended","label":"Blended","priceModifier":0.8}]'::jsonb,
    '["Buz Yok","Az Buzlu","Normal","Ekstra Buzlu","Blended"]'::jsonb,
    '{"calories":120,"fat":4,"carbs":14,"protein":6,"caffeine":70}'::jsonb, 6),
  ('p8', 'Safran Gül Latte', 'Latte', 'İran safranı ve gül suyu ile demlenmiş buharlaştırılmış süt. Espresso X özel üretimi.', 220, 'https://images.pexels.com/photos/7651785/pexels-photo-7651785.jpeg?auto=compress&cs=tinysrgb&w=800', 4.9, true, true, true, true, 200, '{Süt}',
    '[{"id":"s","label":"Küçük","priceModifier":0},{"id":"l","label":"Büyük","priceModifier":10}]'::jsonb,
    '[{"id":"whole","label":"Tam Yağlı Süt","priceModifier":0},{"id":"skim","label":"Yağsız Süt","priceModifier":0},{"id":"oat","label":"Yulaf Sütü","priceModifier":0.6},{"id":"almond","label":"Badem Sütü","priceModifier":0.6},{"id":"soy","label":"Soya Sütü","priceModifier":0.5},{"id":"coconut","label":"Hindistan Cevizi Sütü","priceModifier":0.6}]'::jsonb,
    '[{"id":"none","label":"Şurup Yok","priceModifier":0},{"id":"vanilla","label":"Vanilya","priceModifier":0.5},{"id":"caramel","label":"Karamel","priceModifier":0.5},{"id":"hazelnut","label":"Fındık","priceModifier":0.5},{"id":"pistachio","label":"Antep Fıstığı","priceModifier":0.7},{"id":"lavender","label":"Lavanta Balı","priceModifier":0.7},{"id":"brown-sugar","label":"Kahverengi Şeker","priceModifier":0.5}]'::jsonb,
    '[{"id":"none","label":"Ekstra Yok","priceModifier":0},{"id":"whip","label":"Krema","priceModifier":0.6},{"id":"caramel-drizzle","label":"Karamel Sos","priceModifier":0.5},{"id":"cocoa","label":"Kakao","priceModifier":0.3},{"id":"cinnamon","label":"Tarçın","priceModifier":0.3},{"id":"gold-leaf","label":"Altın Yaprak","priceModifier":2.5}]'::jsonb,
    '[{"id":"hot","label":"Sıcak","priceModifier":0},{"id":"iced","label":"Buzlu","priceModifier":0},{"id":"blended","label":"Blended","priceModifier":0.8}]'::jsonb,
    '["Buz Yok","Az Buzlu","Normal","Ekstra Buzlu","Blended"]'::jsonb,
    '{"calories":200,"fat":8,"carbs":22,"protein":9,"caffeine":154}'::jsonb, 8),
  ('p9', 'Kara Orman Mocha', 'Kahve', 'Double espresso, %70 Venezuelalı bitter çikolata, buharlaştırılmış süt ve kakao kenarlı bardak.', 220, 'https://images.pexels.com/photos/544961/pexels-photo-544961.jpeg?auto=compress&cs=tinysrgb&w=800', 4.7, true, false, false, true, 260, '{Süt,Soya}',
    '[{"id":"s","label":"Küçük","priceModifier":0},{"id":"l","label":"Büyük","priceModifier":10}]'::jsonb,
    '[{"id":"whole","label":"Tam Yağlı Süt","priceModifier":0},{"id":"skim","label":"Yağsız Süt","priceModifier":0},{"id":"oat","label":"Yulaf Sütü","priceModifier":0.6},{"id":"almond","label":"Badem Sütü","priceModifier":0.6},{"id":"soy","label":"Soya Sütü","priceModifier":0.5},{"id":"coconut","label":"Hindistan Cevizi Sütü","priceModifier":0.6}]'::jsonb,
    '[{"id":"none","label":"Şurup Yok","priceModifier":0},{"id":"vanilla","label":"Vanilya","priceModifier":0.5},{"id":"caramel","label":"Karamel","priceModifier":0.5},{"id":"hazelnut","label":"Fındık","priceModifier":0.5},{"id":"pistachio","label":"Antep Fıstığı","priceModifier":0.7},{"id":"lavender","label":"Lavanta Balı","priceModifier":0.7},{"id":"brown-sugar","label":"Kahverengi Şeker","priceModifier":0.5}]'::jsonb,
    '[{"id":"none","label":"Ekstra Yok","priceModifier":0},{"id":"whip","label":"Krema","priceModifier":0.6},{"id":"caramel-drizzle","label":"Karamel Sos","priceModifier":0.5},{"id":"cocoa","label":"Kakao","priceModifier":0.3},{"id":"cinnamon","label":"Tarçın","priceModifier":0.3},{"id":"gold-leaf","label":"Altın Yaprak","priceModifier":2.5}]'::jsonb,
    '[{"id":"hot","label":"Sıcak","priceModifier":0},{"id":"iced","label":"Buzlu","priceModifier":0},{"id":"blended","label":"Blended","priceModifier":0.8}]'::jsonb,
    '["Buz Yok","Az Buzlu","Normal","Ekstra Buzlu","Blended"]'::jsonb,
    '{"calories":260,"fat":11,"carbs":32,"protein":10,"caffeine":165}'::jsonb, 9),
  ('p10', 'Antep Fıstığı Affogato', 'Tatlılar', 'İki top Antep fıstığı dondurması, taze çekilmiş espresso shot içinde boğulmuş. Şatafatlı.', 120, 'https://images.pexels.com/photos/1855214/pexels-photo-1855214.jpeg?auto=compress&cs=tinysrgb&w=800', 4.9, true, false, false, true, 320, '{Süt,Kuruyemiş}',
    '[{"id":"s","label":"Tekli","priceModifier":0},{"id":"m","label":"İkili","priceModifier":45}]'::jsonb,
    '[{"id":"whole","label":"Tam Yağlı Süt","priceModifier":0}]'::jsonb,
    '[{"id":"none","label":"Şurup Yok","priceModifier":0}]'::jsonb,
    '[{"id":"none","label":"Ekstra Yok","priceModifier":0}]'::jsonb,
    '[{"id":"hot","label":"Sıcak","priceModifier":0}]'::jsonb,
    '["Buz Yok"]'::jsonb,
    '{"calories":320,"fat":16,"carbs":38,"protein":8,"caffeine":75}'::jsonb, 10),
  ('p11', 'Bademli Kruvasan', 'Unlu Mamuller', 'Tam yağlı tereyağlı milföy hamuru, frangipane dolgulu, kavrulmuş badem ve pudra şekeri ile.', 75, 'https://images.pexels.com/photos/2135/pexels-photo-2135.jpeg?auto=compress&cs=tinysrgb&w=800', 4.6, true, false, false, true, 380, '{Buğday,Süt,Kuruyemiş,Yumurta}',
    '[{"id":"s","label":"Standart","priceModifier":0}]'::jsonb,
    '[{"id":"whole","label":"Tam Yağlı Süt","priceModifier":0}]'::jsonb,
    '[{"id":"none","label":"Şurup Yok","priceModifier":0}]'::jsonb,
    '[{"id":"none","label":"Ekstra Yok","priceModifier":0}]'::jsonb,
    '[{"id":"hot","label":"Sıcak","priceModifier":0}]'::jsonb,
    '["Buz Yok"]'::jsonb,
    '{"calories":380,"fat":22,"carbs":40,"protein":8,"caffeine":0}'::jsonb, 11),
  ('p13', 'Avokadolu Tost', 'Kahvaltı', 'Ezilmiş avokado, haşlanmış yumurta, acı bal ve micro yeşillikler, ekşi maya üzerinde.', 145, 'https://images.pexels.com/photos/1351238/pexels-photo-1351238.jpeg?auto=compress&cs=tinysrgb&w=800', 4.8, true, false, false, true, 350, '{Buğday,Yumurta}',
    '[{"id":"s","label":"Standart","priceModifier":0}]'::jsonb,
    '[{"id":"whole","label":"Tam Yağlı Süt","priceModifier":0}]'::jsonb,
    '[{"id":"none","label":"Şurup Yok","priceModifier":0}]'::jsonb,
    '[{"id":"none","label":"Ekstra Yok","priceModifier":0}]'::jsonb,
    '[{"id":"hot","label":"Sıcak","priceModifier":0}]'::jsonb,
    '["Buz Yok"]'::jsonb,
    '{"calories":350,"fat":19,"carbs":30,"protein":14,"caffeine":0}'::jsonb, 13),
  ('p15', 'Etiyopya Yirgacheffe Çekirdek', 'Kahve Çekirdeği', '250g tam çekirdek. Yasemin, bergamot ve taş meyve notaları. Açık kavrum, tek menşe.', 380, 'https://images.pexels.com/photos/4109744/pexels-photo-4109744.jpeg?auto=compress&cs=tinysrgb&w=800', 4.9, true, false, false, true, 0, '{}',
    '[{"id":"s","label":"250g","priceModifier":0},{"id":"m","label":"500g","priceModifier":280}]'::jsonb,
    '[{"id":"whole","label":"Tam Yağlı Süt","priceModifier":0}]'::jsonb,
    '[{"id":"none","label":"Şurup Yok","priceModifier":0}]'::jsonb,
    '[{"id":"none","label":"Ekstra Yok","priceModifier":0}]'::jsonb,
    '[{"id":"hot","label":"Sıcak","priceModifier":0}]'::jsonb,
    '["Buz Yok"]'::jsonb,
    '{"calories":0,"fat":0,"carbs":0,"protein":0,"caffeine":0}'::jsonb, 15)
  ON CONFLICT (id) DO NOTHING;

  -- Rewards
  INSERT INTO rewards (id, title, description, points_cost, category, image, is_active) VALUES
  ('r1', 'Herhangi Bir El Yapımı Kahve', 'Herhangi bir boyutta kahve veya espresso içeceğinde kullanın.', 150, 'coffee', 'https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg?auto=compress&cs=tinysrgb&w=800', true),
  ('r2', 'Ücretsiz Tatlı', 'Vitrinimizden herhangi bir tatlı seçin.', 200, 'dessert', 'https://images.pexels.com/photos/1855214/pexels-photo-1855214.jpeg?auto=compress&cs=tinysrgb&w=800', true),
  ('r3', 'Tüm Siparişte %25 İndirim', 'Bir sonraki siparişinizde tek seferlik %25 indirim.', 300, 'discount', 'https://images.pexels.com/photos/312428/pexels-photo-312428.jpeg?auto=compress&cs=tinysrgb&w=800', true),
  ('r4', 'Safran Gül Latte', 'Özel imza içeceğimizin kilidini açın.', 500, 'exclusive', 'https://images.pexels.com/photos/7651785/pexels-photo-7651785.jpeg?auto=compress&cs=tinysrgb&w=800', true),
  ('r5', 'Doğum Günü İkramiyesi', 'Doğum gününüzde herhangi bir içecek + tatlı.', 0, 'birthday', 'https://images.pexels.com/photos/2198032/pexels-photo-2198032.jpeg?auto=compress&cs=tinysrgb&w=800', true),
  ('r6', 'Ücretsiz Boy Yükseltme', 'Herhangi bir içeceği Büyük boyuta yükseltin, bizden.', 80, 'coffee', 'https://images.pexels.com/photos/2074130/pexels-photo-2074130.jpeg?auto=compress&cs=tinysrgb&w=800', true),
  ('r7', 'Çift Puan Günü', '24 saat boyunca tüm alışverişlerde 2x puan kazanın.', 250, 'discount', 'https://images.pexels.com/photos/4109744/pexels-photo-4109744.jpeg?auto=compress&cs=tinysrgb&w=800', true),
  ('r8', 'Etiyopya Yirgacheffe Çekirdek', 'En kaliteli çekirdeklerimizden 250g eve götürün.', 600, 'exclusive', 'https://images.pexels.com/photos/4109744/pexels-photo-4109744.jpeg?auto=compress&cs=tinysrgb&w=800', true)
  ON CONFLICT (id) DO NOTHING;
END $$;
